services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=myapp_development
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3000"  # Assuming React runs on port 3000 inside the container
    environment:
      - CHOKIDAR_USEPOLLING=true  # Helps with hot reloading in Docker

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
